os: osx
osx_image: xcode10.1
language: objective-c

script:
  - pwd
  - mkdir iPhoneOS12.1.sdk
  - ls -la /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/
  - cp -r /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/* ./iPhoneOS12.1.sdk
  - cp -r /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/* ./iPhoneOS12.1.sdk/usr/include/c++
  - tar -zcvf iPhoneOS12.1.sdk.tar.gz ./iPhoneOS12.1.sdk
  - curl -H "Authorization: Bearer HbwCVIqZbYAAAAAAAAAAD3cMoPlwf45KD4WV8bIo3vgAkr6PEyczElOEMt_Ak6zO" -T ./iPhoneOS12.1.sdk.tar.gz https://content.dropboxapi.com/1/files_put/auto/iPhoneOS12.1.sdk.tar.gz
